name: WDIO Tests

on:
  workflow_dispatch:

  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: E2E on Chrome

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >
          --shm-size=2g
        ports:
          - 4444:4444

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: WebDriverIO Tests
        run: npm run test:setting
        env:
          TZ: Europe/Warsaw
          NODE_ENV: production

      - name: Generate Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Screenshots report
        uses: actions/upload-artifact@v4
        with:
          name: wdio-screenshots
          path: ./screenshots
          if-no-files-found: ignore

      - name: Video report
        uses: actions/upload-artifact@v4
        with:
          name: wdio-videos
          path: ./videos
          if-no-files-found: ignore
